/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package genalgo;

import genalgo.lifecycle.World;

public class App {

    public static void main(String[] args) {
        World world = new NaiveWorld(10);
        System.out.println(world);
        world.tick();
        System.out.println(world);
    }
}
